# Generated by Django 4.1.4 on 2022-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=255)),
                ('prerequisite', models.CharField(default='None', max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
