# Generated by Django 4.1.4 on 2022-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('role', models.CharField(choices=[('Professor', 'Professor'), ('Alumni', 'Alumni')], max_length=10)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
    ]
