# Generated by Django 4.1.4 on 2022-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_course_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
