# Generated by Django 4.1.4 on 2022-12-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alumni_news_professor_delete_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='thumbnail',
        ),
    ]
