# Generated by Django 4.1.4 on 2022-12-20 16:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_alumni_id_alter_alumni_picture_alter_news_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
